Repository Radio-Premium/RadioPremium-BE, pull requests merged in 2025-05, with the labels that each got.

#2 chore: 백엔드 프로젝트 초기세팅
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  commitlint.config.cjs
  eslint.config.mjs
  package-lock.json
  package.json
Labels: ⚙️setting

#7 feat: Supabase 연동
  package.json
  src/server.js
  src/services/supabaseClient.js
Labels: ✨feat, ⚙️setting

#15 feat: 관심 채널 관련 API 구현
  src/controllers/userController.js
  src/routes/users/[userId].js
  src/services/userService.js
Labels: ✨feat

#23 feat: 신규 사용자 등록 API 구현
  src/controllers/userController.js
  src/routes/users/index.js
  src/server.js
  src/services/userService.js
  src/utils/caseConverter.js
Labels: ✨feat

#25 feat: 관심 채널 갱신 API 구현
  src/controllers/userController.js
  src/routes/users/[userId].js
  src/services/userService.js
Labels: ✨feat

#26 feat: 사용자 설정 변경 API 구현
  src/controllers/userSettingController.js
  src/routes/users/[userId].js
  src/services/userSettingService.js
Labels: ✨feat

#27 feat: 광고 제보 등록 API 구현
  src/controllers/reportController.js
  src/routes/report/index.js
  src/server.js
  src/services/reportService.js
  src/validators/reportValidator.js
Labels: ✨feat
