Repository Radio-Premium/RadioPremium-BE, pull requests merged in 2025-06, with the labels that each got.

#31 refactor: HTTP 상태 코드 및 응답 메시지 상수화
  src/constants/httpStatus.js
  src/constants/index.js
  src/constants/messages.js
  src/controllers/ad-keywords/adKeywordController.js
  src/controllers/radio-channels/radioChannelController.js
  src/controllers/reports/reportController.js
  src/controllers/users/userController.js
  src/controllers/users/userInterestChannelController.js
  src/controllers/users/userSettingController.js
  src/services/ad-keywords/adKeywordService.js
  src/services/radio-channels/radioChannelService.js
  src/services/reports/reportService.js
  src/services/users/userInterestChannelService.js
  src/services/users/userService.js
  src/services/users/userSettingService.js
  src/validators/channelValidator.js
  src/validators/reportValidator.js
  src/validators/userValidator.js
Labels: 🛠️refactor

#33 chore: 백엔드 socket.io 설치
  package.json
Labels: 💡chore

#37 feat: 방송사 및 is_api_exposed 조건에 따른 라디오 스트리밍 URL 처리 로직 구현
  src/services/radio-channels/radioChannelService.js
  src/sockets/index.js
Labels: ✨feat

#43 feat: main, dev 브랜치용 CI/CD 구축
  .github/workflows/deploy.yml
  package-lock.json
  package.json
Labels: 🌐deploy

#47 fix: MODULE_NOT_FOUND(radioChannelService.js) 에러 해결
  src/services/radio-channels/radioChannelService.js
  src/utils/sendStreamingUrlToWhisper.js
Labels: 🐞bug, 🔧fix, 🚨hotfix

#49 feat: 광고 키워드 기반 광고 탐지 로직 구현
  src/cache/adKeywordCache.js
  src/init/loadAdKeywords.js
  src/server.js
  src/sockets/handlers/transcribedTextHandler.js
  src/sockets/handlers/whisperHandler.js
  src/sockets/index.js
Labels: ✨feat

#53 feat: 광고 감지 여부에 따른 whisper 서버 연결
  src/controllers/radio-channels/radioChannelController.js
  src/services/radio-channels/radioChannelService.js
Labels: ✨feat

#55 feat: 광고 없는 채널 중 랜덤 채널 반환 API 구현
  src/controllers/radio-channels/radioChannelController.js
  src/routes/radio-channels/index.js
  src/services/radio-channels/radioChannelService.js
Labels: ✨feat

#58 feat: userId 기준 소켓 매핑 구현
  src/controllers/radio-channels/radioChannelController.js
  src/services/radio-channels/radioChannelService.js
  src/sockets/handlers/clientHandler.js
  src/sockets/handlers/radioTextHandler.js
  src/sockets/handlers/transcribedTextHandler.js
  src/sockets/handlers/userConnectionHandler.js
  src/sockets/handlers/whisperHandler.js
  src/sockets/index.js
  src/utils/sendStreamingUrlToWhisper.js
Labels: ✨feat

#59 feat: 광고 종료 감지 및 이전 채널 복귀 구현
  src/sockets/handlers/transcribedTextHandler.js
  src/sockets/handlers/userConnectionHandler.js
Labels: ✨feat

#62 fix: Whisper 요청 처리를 위한 /whisper API 추가
  src/controllers/whisper/whisperController.js
  src/routes/whisper/index.js
  src/server.js
  src/services/radio-channels/radioChannelService.js
Labels: 🔧fix

#73 chore: AWS 계정 변경에 따른 GitHub Actions 워크플로우 수정
  .github/workflows/deploy.yml
Labels: 💡chore

#77 chore: 소켓 서버 CORS 설정 추가
  src/constants/env.js
  src/server.js
  src/sockets/index.js
Labels: 💡chore

#79 feat: 머신러닝 + 키워드 기반 광고 탐지 로직 개선
  src/sockets/handlers/transcribedTextHandler.js
Labels: ✨feat

#81 refactor: Whisper 요청 경로 및 사용자 설정 메서드 변경
  src/routes/users/index.js
  src/utils/sendStreamingUrlToWhisper.js
Labels: 🛠️refactor

#83 refactor: 에러 응답 유틸 함수 분리 및 중복 코드 제거
  src/controllers/radio-channels/radioChannelController.js
  src/controllers/users/userController.js
  src/controllers/users/userInterestChannelController.js
  src/controllers/users/userSettingController.js
  src/utils/errorResponse.js
  src/validators/channelValidator.js
  src/validators/reportValidator.js
  src/validators/userValidator.js
Labels: 🛠️refactor
